name: interval_timer
description: HIIT timer for interval training.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_colorpicker: ^0.4.0
  numberpicker: ^1.3.0
  audioplayers: ^0.18.3
  sound_mode: 1.0.2
  flutter_local_notifications: 5.0.0+1
  flutter_launcher_icons: ^0.9.0
  responsive_flutter: ^0.0.4
  percent_indicator: ^3.0.1
  wakelock: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  assets:
    - assets/chime.mp3
    - assets/alert_notification.mp3
    - assets/positive_tone_1.mp3
    - assets/positive_tone_2.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
